/* Reino · base de dados das telas (TODO AI, 22/09).
   Os dados de demonstração foram apagados a pedido do fundador: o app mostra só o que vem do
   banco. Aqui ficam apenas as REGRAS do Reino (títulos, quem fala no Bate Papo, grupos do feed)
   e o formato vazio de cada coleção, para as telas que ainda não têm tabela no banco abrirem
   no estado vazio em vez de quebrar. Os dados antigos estão no git (commit anterior a este) e
   em arquivo/dados-demo/. */
window.BABEL_DEMO = {"perfil":{"nome":"","titulo":"","cidade":"","uf":"","bairro":""},"kpis":[],"feed":[],"match":[],"metricas":[],"conquistas":[],"minhaGuilda":{"nome":"","lider":"","pontos":0,"membros":[]},"guildas":[],"titulos":[{"nome":"Imperador","mensalidade":997,"descricao":"Comanda o mapa do Brasil inteiro.","mapa":"Brasil","beneficios":["Mapa do Brasil inteiro","Grupo de Imperador no feed de negócios"]},{"nome":"Rei","mensalidade":497,"descricao":"Comanda o Brasil dividido por regiões.","mapa":"Brasil por regiões","beneficios":["Mapa do Brasil por regiões","Grupo de Rei no feed de negócios"]},{"nome":"Príncipe","mensalidade":247,"descricao":"Comanda uma região e seus estados.","mapa":"Região com estados","beneficios":["Mapa da região com os estados","Grupo de Príncipe no feed de negócios"]},{"nome":"Duque","mensalidade":97,"descricao":"Comanda um estado e suas cidades.","mapa":"Estado com cidades","beneficios":["Mapa do estado com as cidades","Grupo de Duque no feed de negócios"]},{"nome":"Marquês","mensalidade":77,"descricao":"Fala no Bate Papo do Reino.","mapa":"Estado com cidades","beneficios":["Inteligência de Mercado do Reino","Envia mensagem no Bate Papo do Reino"]},{"nome":"Conde","mensalidade":67,"descricao":"Destaque em uma cidade.","mapa":"Estado com cidades","beneficios":["E-mail próprio","Gestor Financeiro","Perfil verificado","Vitrine destacada"]},{"nome":"Visconde","mensalidade":57,"descricao":"Primeiro degrau da nobreza.","mapa":"Estado com cidades","beneficios":["Perfil no Reino","Acesso ao Clube de Benefícios"]},{"nome":"Barão","mensalidade":47,"descricao":"Entrada no Reino.","mapa":"Estado com cidades","beneficios":["Perfil no Reino"]}],"regras":{"alcanceMapa":{"Imperador":"Brasil","Rei":"Brasil por regiões","Príncipe":"Região com estados"},"alcanceMapaPadrao":"Estado com cidades","chatFala":["Marquês","Duque","Príncipe","Rei","Imperador"]},"noticias":[],"academy":[],"eventos":[],"gruposFeed":["Grupo de Imperador","Grupo de Rei","Grupo de Príncipe","Grupo de Duque"],"rede":{"nos":[],"raios":[]},"vitrinePremium":[],"afiliado":{"link":"","indicados":0,"comissoesPendentes":0,"nivel":"","proximo":"","progresso":0},"vendas":[],"statusNegocios":[],"negociosSemana":{"pontos":[],"rotulos":[]},"alertas":[],"beneficios":[],"acessos":{"visitas":[],"rotulos":[],"origem":[],"resumo":[]},"conversas":[],"mensagens":[],"ativos":[],"regioes":[],"notificacoes":[],"revista":[]};

/* mesmas rotas que o antigo dados-demo.js respondia, sempre vazias (menos títulos e filtros) */
(function () {
  const VAZIOS = {"perfil":{"nome":"","titulo":"","cidade":"","uf":"","bairro":""},"reino/kpis":{"empresas":{"valor":0,"variacao":0},"avaliacoes":{"valor":0,"variacao":0},"cidades":{"valor":0,"variacao":0},"notaMedia":{"valor":0,"variacao":0,"unidadeVariacao":""}},"reino/regioes":[],"reino/mapa":{"total":0,"regioes":{"sudeste":0,"sul":0,"nordeste":0,"centro-oeste":0,"norte":0},"estados":{"SP":0,"MG":0,"RJ":0,"ES":0,"PR":0,"SC":0,"RS":0,"BA":0,"PE":0,"CE":0,"GO":0,"DF":0,"MT":0,"AM":0,"PA":0,"AC":0,"AL":0,"AP":0,"MA":0,"MS":0,"PB":0,"PI":0,"RN":0,"RO":0,"RR":0,"SE":0,"TO":0},"cidades":[]},"reino/filtros":{"nichos":[{"nome":"Advocacia"},{"nome":"Alimentação"},{"nome":"Beleza"},{"nome":"Construção"},{"nome":"Contabilidade"},{"nome":"Educação"},{"nome":"Energia"},{"nome":"Financeiro"},{"nome":"Imobiliária"},{"nome":"Logística"},{"nome":"Marketing"},{"nome":"Pet"},{"nome":"Saúde"},{"nome":"Tecnologia"}],"estados":[{"nome":"Acre"},{"nome":"Alagoas"},{"nome":"Amapá"},{"nome":"Amazonas"},{"nome":"Bahia"},{"nome":"Ceará"},{"nome":"Distrito Federal"},{"nome":"Espírito Santo"},{"nome":"Goiás"},{"nome":"Maranhão"},{"nome":"Mato Grosso"},{"nome":"Mato Grosso do Sul"},{"nome":"Minas Gerais"},{"nome":"Pará"},{"nome":"Paraíba"},{"nome":"Paraná"},{"nome":"Pernambuco"},{"nome":"Piauí"},{"nome":"Rio de Janeiro"},{"nome":"Rio Grande do Norte"},{"nome":"Rio Grande do Sul"},{"nome":"Rondônia"},{"nome":"Roraima"},{"nome":"Santa Catarina"},{"nome":"São Paulo"},{"nome":"Sergipe"},{"nome":"Tocantins"}],"cidades":[]},"reino/empresas":[],"reino/reputacao":{"media":0,"total":0,"distribuicao":[]},"reino/analises":{"cadastros":[],"nichos":[]},"reino/match":[],"reino/vitrine":[],"reino/titulos":[{"nome":"Imperador","mensalidade":997,"descricao":"Comanda o mapa do Brasil inteiro."},{"nome":"Rei","mensalidade":497,"descricao":"Comanda o Brasil dividido por regiões."},{"nome":"Príncipe","mensalidade":247,"descricao":"Comanda uma região e seus estados."},{"nome":"Duque","mensalidade":97,"descricao":"Comanda um estado e suas cidades."},{"nome":"Conde","mensalidade":67,"descricao":"Destaque em uma cidade."},{"nome":"Barão","mensalidade":47,"descricao":"Entrada no Reino."}],"reino/bairros":[],"reino/empresarios":[],"conquistas/resumo":{"progresso":0,"tituloAtual":"","proximoTitulo":"","metricas":[]},"conquistas":[],"social/feed":[],"guildas/minha":{"nome":"","lider":"","pontos":0,"membros":[]},"guildas":[],"afiliado":{"codigo":"","link":"","indicados":0,"comissoesPendentes":0},"afiliado/resolver":{"nome":""},"noticias":[],"busca-inteligente":{"resposta":"","empresas":[]},"revista":[],"notificacoes":[],"mensagens":[],"preferencias":null};
  window.BabelDemo = function (recurso) {
    const v = VAZIOS[recurso];
    return v === undefined ? [] : JSON.parse(JSON.stringify(v));
  };
})();
